### ISSUE TITLE
Práctica 7 Equipo Sandra Velasco y Ángeles Martínez

### ISSUE THREAD

**Issue by SANDRAVELASCO** [SistemasTecTlaxiaco/practica-final-de-hilos-equipo-topicos-as#2]
[Practica7 Equipo_Sandra_Angeles.pdf](https://github.com/SistemasTecTlaxiaco/practica-final-de-hilos-equipo-topicos-as/files/8536041/Practica7.Equipo_Sandra_Angeles.pdf)

**Comment by Yareli-Perez** [comment]
calificación 9.7 =  19.4 %

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
